version: '3.8'

services:
  traefik:
    image: docker.io/traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=DEBUG
      #- --providers.docker=true
      - --providers.file.directory=/config
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
    ports:
      - "443:443"
    volumes:
      - ./traefik/config:/config:ro
      - ./traefik/certs:/certs:ro
    networks:
      - web

  keycloak:
    image: docker.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    command: start-dev --import-realm
    volumes:
      - ./keycloak/demo-realm.json:/opt/keycloak/data/import/demo-realm.json:ro
      - keycloak-data:/opt/keycloak/data
    # No direct port exposure - all traffic goes through Traefik
    environment:
      KC_HOSTNAME: "https://localhost/keycloak"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
      KC_HTTP_RELATIVE_PATH: "/keycloak"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: 8080
      KC_PROXY_HEADERS: xforwarded
      KC_ADMIN: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    networks:
      - web

  demo-app:
    build: ./app
    container_name: demo-app
    restart: unless-stopped
    # No direct port exposure - all traffic goes through Traefik
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: https://localhost/keycloak
      KEYCLOAK_INTERNAL_URL: http://keycloak:8080/keycloak
      KEYCLOAK_REALM: demo
      KEYCLOAK_CLIENT_ID: demo-app
      KEYCLOAK_CLIENT_SECRET: demo-app-secret
      HTTP_PORT: 3000
    networks:
      - web

  # Network debugging container with useful tools
  nettools:
    image: docker.io/nicolaka/netshoot:latest
    container_name: nettools
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - web
    command: sleep infinity

networks:
  web:
    driver: bridge

volumes:
  keycloak-data: