version: '3.8'

services:
  traefik:
    image: docker.io/traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=INFO
      - --providers.file.directory=/config
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
    ports:
      - "443:443"
    volumes:
      - ./traefik/config:/config:ro
      - ./traefik/certs:/certs:ro
    networks:
      - web

  keycloak-db:
    image: docker.io/postgres:15-alpine
    container_name: keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - keycloak_internal

  keycloak:
    image: docker.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    command: start --import-realm
    volumes:
      - ./traefik/certs:/opt/keycloak/conf/certs:ro
      - ./keycloak/demo-realm.json:/opt/keycloak/data/import/demo-realm.json:ro
    # No direct port exposure - all traffic goes through Traefik
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HOSTNAME: keycloak.localhost
      KC_HOSTNAME_STRICT: "false"
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/certs/localhost.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/certs/localhost.key
      KC_HTTPS_PORT: 8443
      KC_HTTP_ENABLED: "false"
      KC_PROXY: edge
      KC_PROXY_HEADERS: xforwarded
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      - keycloak-db
    networks:
      web:
        aliases:
          - keycloak.localhost
      keycloak_internal:

  demo-app:
    build: ./app
    container_name: demo-app
    restart: unless-stopped
    volumes:
      - ./traefik/certs:/app/certs:ro
    # No direct port exposure - all traffic goes through Traefik
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: https://keycloak.localhost
      KEYCLOAK_INTERNAL_URL: https://keycloak:8443
      KEYCLOAK_REALM: demo
      KEYCLOAK_CLIENT_ID: demo-app
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      HTTPS_PORT: 3443
      SSL_CERT: /app/certs/localhost.crt
      SSL_KEY: /app/certs/localhost.key
    networks:
      - web

networks:
  web:
    external: false
  keycloak_internal:
    external: false

volumes:
  keycloak_db_data: