#!/bin/bash

# Simple script to demonstrate OIDC Authorization Code Flow testing

echo "🔐 OpenID Connect Authorization Code Flow - Demo"
echo "================================================="
echo ""
echo "Your application is configured for OIDC Authorization Code Flow with:"
echo ""
echo "✅ **Client Configuration:**"
echo "   - Client ID: demo-app"
echo "   - Client Type: Confidential (uses client secret)"
echo "   - Flow: Authorization Code Flow (standardFlowEnabled: true)"
echo "   - Implicit Flow: Disabled (more secure)"
echo "   - Protocol: openid-connect"
echo ""
echo "✅ **Application Features:**"
echo "   - Session management"
echo "   - Automatic token refresh"
echo "   - Secure logout"
echo "   - User info extraction"
echo ""
echo "🌐 **Access the Application:**"
echo "   Since we're in WSL, use one of these methods:"
echo ""
echo "   Method 1 (with /etc/hosts entry):"
echo "   Add to /etc/hosts: 127.0.0.1 app.localhost keycloak.localhost"
echo "   Then visit: http://app.localhost:8080"
echo ""
echo "   Method 2 (direct with headers):"
echo "   curl -H 'Host: app.localhost' http://localhost:8080"
echo ""
echo "📝 **Authorization Code Flow Steps:**"
echo "   1. User visits protected page"
echo "   2. App redirects to Keycloak: /realms/demo/protocol/openid-connect/auth"
echo "   3. User authenticates with Keycloak"
echo "   4. Keycloak redirects back with authorization code"
echo "   5. App exchanges code for access token (server-side)"
echo "   6. App uses token to get user info"
echo "   7. User is logged in"
echo ""
echo "🧪 **Manual Testing (without browser):**"
echo ""
echo "1. Get authorization URL:"
AUTH_URL="http://localhost:8080/realms/demo/protocol/openid-connect/auth?client_id=demo-app&redirect_uri=http://localhost:3000/callback&response_type=code&scope=openid&state=test123"
echo "   $AUTH_URL"
echo ""
echo "2. After login, you'll get redirected to:"
echo "   http://localhost:3000/callback?code=AUTH_CODE&state=test123"
echo ""
echo "3. Exchange code for token:"
echo "   curl -X POST http://localhost:8080/realms/demo/protocol/openid-connect/token \\"
echo "     -H 'Host: keycloak.localhost' \\"
echo "     -H 'Content-Type: application/x-www-form-urlencoded' \\"
echo "     -d 'grant_type=authorization_code' \\"
echo "     -d 'client_id=demo-app' \\"
echo "     -d 'client_secret=demo-app-secret' \\"
echo "     -d 'code=YOUR_AUTH_CODE' \\"
echo "     -d 'redirect_uri=http://localhost:3000/callback'"
echo ""
echo "🔗 **OIDC Endpoints (configured automatically):**"
echo "   - Authorization: /realms/demo/protocol/openid-connect/auth"
echo "   - Token: /realms/demo/protocol/openid-connect/token"
echo "   - UserInfo: /realms/demo/protocol/openid-connect/userinfo"
echo "   - Logout: /realms/demo/protocol/openid-connect/logout"
echo "   - Well-known: /realms/demo/.well-known/openid_configuration"
echo ""
echo "📱 **Demo Application Routes:**"
echo "   - GET /          - Home page (shows login status)"
echo "   - GET /protected - Protected page (triggers OIDC flow)"
echo "   - GET /logout    - Logout (OIDC logout)"
echo ""
echo "👤 **Test User (create manually in Keycloak admin):**"
echo "   - Username: demo-user"
echo "   - Password: demo123"
echo ""
echo "🔧 **Keycloak Admin Access:**"
echo "   1. Add to /etc/hosts: 127.0.0.1 keycloak.localhost"
echo "   2. Visit: http://keycloak.localhost:8080"
echo "   3. Login with admin / your_secure_admin_password"
echo "   4. Create 'demo' realm manually"
echo "   5. Import client config from keycloak/demo-realm.json"
echo ""
echo "🎉 Your OIDC Authorization Code Flow is ready!"